In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.4'

## CREATE AND READ

### 1D ARRAY

In [4]:
arr1 = np.array([1,2,3])

In [5]:
arr1

array([1, 2, 3])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(3,)

In [8]:
arr1.dtype

dtype('int64')

In [9]:
arr1.ndim

1

In [10]:
arr1.size

3

### 2D ARRAY

In [12]:
arr2 = np.array([[1,2,3,4,5],[1,2,3,12,21]])

In [13]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3, 12, 21]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape # {row, col}

(2, 5)

In [16]:
arr2.dtype

dtype('int64')

### 3D ARRAY

In [26]:
arr3 = np.array([[[1,2,3,4], [1,2,3,12]], [[1,12,11,12], [12,11,21,12]]])

In [27]:
arr3

array([[[ 1,  2,  3,  4],
        [ 1,  2,  3, 12]],

       [[ 1, 12, 11, 12],
        [12, 11, 21, 12]]])

In [28]:
arr3.ndim

3

In [29]:
arr3.size

16

In [31]:
arr3.shape #{Layer, Row, Col}

(2, 2, 4)

### CREATE RENDOM ARRAY

In [32]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.84669552, 0.3575985 , 0.68980528],
        [0.04304196, 0.14798922, 0.03348769]],

       [[0.97125982, 0.57309422, 0.96460561],
        [0.35187111, 0.25605882, 0.87808451]],

       [[0.23915579, 0.26545116, 0.96247359],
        [0.45410352, 0.72729106, 0.9435198 ]]])

In [33]:
randomArr.dtype

dtype('float64')

In [36]:
zeros = np.zeros((1,2,3))

In [37]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [38]:
zeros.dtype

dtype('float64')

In [40]:
zeros.ndim

3

In [41]:
full = np.full((1,2,3),0)

In [42]:
full

array([[[0, 0, 0],
        [0, 0, 0]]])

In [43]:
ones = np.ones((1,2,3))

In [44]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [45]:
ones.ndim

3

In [46]:
ones.dtype

dtype('float64')

In [47]:
arr3

array([[[ 1,  2,  3,  4],
        [ 1,  2,  3, 12]],

       [[ 1, 12, 11, 12],
        [12, 11, 21, 12]]])

In [50]:
arr3[0]

array([[ 1,  2,  3,  4],
       [ 1,  2,  3, 12]])

In [52]:
arr3[0][0][2]

np.int64(3)

In [54]:
arr3[0:1]

array([[[ 1,  2,  3,  4],
        [ 1,  2,  3, 12]]])

In [57]:
arr3[-1]

array([[ 1, 12, 11, 12],
       [12, 11, 21, 12]])

In [58]:
arr3[1,0,1]

np.int64(12)

## UPDATE & DELETE

In [59]:
a1 = np.random.rand(2,3,4)
a2 = np.random.rand(2,3,4)

In [60]:
a1

array([[[0.91012074, 0.02840792, 0.66842985, 0.30016262],
        [0.63430271, 0.27719038, 0.4966176 , 0.42649659],
        [0.00306996, 0.1145964 , 0.23021661, 0.33557938]],

       [[0.44349872, 0.64516746, 0.39789041, 0.89888892],
        [0.40433166, 0.74853538, 0.45841902, 0.93406602],
        [0.12462462, 0.9050509 , 0.72672081, 0.41012683]]])

In [61]:
a2

array([[[0.80019493, 0.00504326, 0.09273631, 0.26564114],
        [0.40483046, 0.6642407 , 0.74118346, 0.43389246],
        [0.12822849, 0.42627838, 0.1256039 , 0.33823509]],

       [[0.71884675, 0.37590189, 0.91430662, 0.88083561],
        [0.60653032, 0.85111214, 0.02014335, 0.36094554],
        [0.20916556, 0.20659425, 0.14066177, 0.01133362]]])

### BASIC MATH OPERATIONS

In [62]:
np.add(a1,a2)

array([[[1.71031568, 0.03345118, 0.76116616, 0.56580377],
        [1.03913317, 0.94143108, 1.23780106, 0.86038904],
        [0.13129845, 0.54087478, 0.3558205 , 0.67381447]],

       [[1.16234547, 1.02106935, 1.31219704, 1.77972454],
        [1.01086197, 1.59964752, 0.47856236, 1.29501156],
        [0.33379018, 1.11164516, 0.86738257, 0.42146046]]])

In [63]:
np.subtract(a1,a2)

array([[[ 0.10992581,  0.02336466,  0.57569355,  0.03452148],
        [ 0.22947226, -0.38705032, -0.24456586, -0.00739587],
        [-0.12515852, -0.31168198,  0.10461271, -0.00265571]],

       [[-0.27534803,  0.26926558, -0.51641621,  0.01805331],
        [-0.20219866, -0.10257676,  0.43827567,  0.57312048],
        [-0.08454094,  0.69845665,  0.58605904,  0.39879321]]])

In [64]:
np.divide(a1,a2)

array([[[1.13737379e+00, 5.63284835e+00, 7.20785512e+00, 1.12995531e+00],
        [1.56683545e+00, 4.17304115e-01, 6.70033301e-01, 9.82954602e-01],
        [2.39413575e-02, 2.68829971e-01, 1.83287788e+00, 9.92148334e-01]],

       [[6.16958653e-01, 1.71631877e+00, 4.35182686e-01, 1.02049566e+00],
        [6.66630580e-01, 8.79479145e-01, 2.27578392e+01, 2.58783088e+00],
        [5.95818056e-01, 4.38081353e+00, 5.16644169e+00, 3.61867366e+01]]])

In [65]:
np.multiply(a1,a2)

array([[[7.28274008e-01, 1.43268503e-04, 6.19877151e-02, 7.97355425e-02],
        [2.56785060e-01, 1.84121132e-01, 3.68084751e-01, 1.85053651e-01],
        [3.93656849e-04, 4.88499695e-02, 2.89161028e-02, 1.13504721e-01]],

       [[3.18807612e-01, 2.42519667e-01, 3.63793839e-01, 7.91773375e-01],
        [2.45239408e-01, 6.37087545e-01, 9.23409257e-03, 3.37146965e-01],
        [2.60671787e-02, 1.86978316e-01, 1.02221832e-01, 4.64822295e-03]]])

### SATISTICAL OPERATIONS

In [67]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np. log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [68]:
sqrt

np.float64(5.0)

In [70]:
abs

np.int64(2)

In [71]:
power

np.int64(256)

In [72]:
log

np.float64(3.2188758248682006)

In [73]:
mins

np.float64(0.0030699640645130977)

In [74]:
maxs

np.float64(0.9143066228512017)

### UPDATE

In [77]:
arr3

array([[[ 1,  2,  3,  4],
        [ 1,  2,  3, 12]],

       [[ 1, 12, 11, 12],
        [12, 11, 21, 12]]])

In [78]:
arr3[0, 0, 2] = 500

In [79]:
arr3

array([[[  1,   2, 500,   4],
        [  1,   2,   3,  12]],

       [[  1,  12,  11,  12],
        [ 12,  11,  21,  12]]])

In [81]:
arr3.sort()

In [82]:
arr3

array([[[  1,   2,   4, 500],
        [  1,   2,   3,  12]],

       [[  1,  11,  12,  12],
        [ 11,  12,  12,  21]]])

In [83]:
# RESHAPE
arr3.shape

(2, 2, 4)

In [101]:
arr3__reshape = arr3.reshape((4,-1))
arr3__reshape

array([[  1,   2,   4, 500],
       [  1,   2,   3,  12],
       [  1,  11,  12,  12],
       [ 11,  12,  12,  21]])

### APPENDING & INSERTING

In [102]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [120]:
# CREATE A NEW ARRAY
new_array = np.ones((1,2,3))

In [121]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [122]:
appd = np.append(zeros, new_array, axis=1) #axis 0 = Row, axis 1 = Col

In [123]:
appd

array([[[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [124]:
### INSERTING
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [125]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [137]:
inserted_array = np.insert(zeros, 1, new_array, axis=0)

In [138]:
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### DELETE

In [139]:
arr4 = np.random.rand(3,2,3)

In [140]:
arr4

array([[[0.23904671, 0.50771255, 0.33354891],
        [0.46668981, 0.44316933, 0.00739635]],

       [[0.9865405 , 0.40480088, 0.348606  ],
        [0.18507351, 0.0633916 , 0.19225917]],

       [[0.32988392, 0.89595427, 0.69601152],
        [0.87698025, 0.12682207, 0.24809217]]])

In [144]:
# DELETE THE ARRAY 
arr5 = np.delete(arr4, 0, axis=1)

In [145]:
arr5

array([[[0.46668981, 0.44316933, 0.00739635]],

       [[0.18507351, 0.0633916 , 0.19225917]],

       [[0.87698025, 0.12682207, 0.24809217]]])

In [146]:
np.save("new_array", arr4)

In [147]:
np.load("new_array.npy")

array([[[0.23904671, 0.50771255, 0.33354891],
        [0.46668981, 0.44316933, 0.00739635]],

       [[0.9865405 , 0.40480088, 0.348606  ],
        [0.18507351, 0.0633916 , 0.19225917]],

       [[0.32988392, 0.89595427, 0.69601152],
        [0.87698025, 0.12682207, 0.24809217]]])